// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJoyGbJ3U2s0QnbHmDw_IrEmDr9YDV5M',
    appId: '1:939899360394:android:4392b72108ffb18c8d8973',
    messagingSenderId: '939899360394',
    projectId: 'the-placee',
    storageBucket: 'the-placee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0GOauMZlr5DuTBQ-_7-v6JAoav4yqmT4',
    appId: '1:939899360394:ios:b8891b252bbb73918d8973',
    messagingSenderId: '939899360394',
    projectId: 'the-placee',
    storageBucket: 'the-placee.appspot.com',
    androidClientId: '939899360394-1fg3p4q09g8s26goo45irm8sm9r1auhv.apps.googleusercontent.com',
    iosClientId: '939899360394-5pvj13u90sakj2e9e0h857ea9aage3v1.apps.googleusercontent.com',
    iosBundleId: 'dev.iremide.thePlacee',
  );
}
